### ISSUE TITLE
[Meta] Strings to-do list

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#623]
Build: 1224
Per the UX spec (Home: v2.1, Menu: v2.1)
Edited: 09/25 16:53
#### 0-1. Onboarding - first
- [x] "Thanks for choosing Firefox Rocket"
- [x] "A browser tailor-made for Indonesia by Mozilla, the non-profit committed to a free and open web."
- [x] "NEXT"
#### 0-2. Onboarding - second
- [x] "Browse faster than ever"
- [x] "Use turbo mode to block ads and trackers so you can browse at blazing speeds. If sites seems broken, just tap off the turbo mode switch in the menu."
- [x] "Turbo mode"
- [x] "NEXT"
#### 0-3. Onboarding - third
- [x] "Save data = Save money"
- [x] "Blocking ads and online trackers not only speeds up browsing, it saves data. Save even more when you block images."
- [x] "NEXT"
#### 0-4. Onboarding - forth
- [x] "Screenshot everything"
- [x] "Take screenshots of entire web pages. View a screenshot offline (without using data) or tap it to revisit the web page."
- [x] "OK, GOT IT!"
#### 1-1. Home | Long tap on top site
- [x] "Firefox Rocket"
- [x] "Search or enter address"
- [x] "Remove"
#### 1-2. Home | Menu
- [x] "Downloads"
- [x] "History"
- [x] "My shots"
- [x] "Turbo mode"
- [x] "Block image"
- [x] "Clear cache"
- [x] "Settings"
#### 2-1. HOME | Menu | Downloads empty
- [x] "No downloads"
#### 2-2-1. Home | Menu | Downloads with items
- [x] "CANCEL"
- [x] "downloading"
#### 2-2-2. Home | Menu | Downloads with items
- [x] "failed"
- [ ] _"canceled"_ (P 1.5)
- [x] "paused"
#### 2-3. Home | Menu | Downloads with items | item_menu
- [x] "Remove from list"
- [x] "Delete file"
#### 2-4. Home | Menu | Downloads with items | item_menu | Delete file
- [x] "file_name* was deleted" (toast)
#### 2-5. Home | Menu | Downloads with items | tap on a missing file
- [x] "Cannot find the file" (toast)
#### 2-6. Home | Menu | Downloads with items | downloading_menu | CANCEL
- [x] "Download canceled" (toast)
#### 3-1. Home | Menu | History empty
- [x] "No browsing history"
#### 3-2. Home | Menu | History item | item menu (with CLEAR BROWSING HISTORY)
- [x] "CLEAR BROWSING HISTORY"
- [x] "Delete"
#### 3-3. Home | Menu | History item | CLEAR BROWSING HISTORY
- [x] "Clear all browsing history?"
- [x] "CANCEL"
- [x] "CLEAR"
#### 4-1. Home | Menu | My shots | No screenshots
- [x] "No Screenshots"
- [x] "Tap %capture_icon% on the menu to capture an entire web page."
#### 4-2. Home | Menu | My shots | Screenshot item | info
- [x] "Info"
- [x] "Time:"
- [x] "Resolution:"
- [x] "Size:"
- [x] "Title:"
- [x] "URL:"
- [x] "OK"
#### 4-3. Home | Menu | My shots | Screenshot item | Delete
- [x] "Delete this image?"
- [x] "CANCEL"
- [x] "DELETE"
#### 4-4. Home | Menu | My shots | Screenshot item | Delete | DELETE
- [x] "Screenshot deleted" (toast)
#### 4-5. Home | Menu | My shots | Tap on missing screenshot
- [x] "Cannot display the screenshot"
#### 5-1. Home | Menu | Turbo mode | -> off
- [x] "Turbo mode disabled" (toast)
#### 5-2. Home | Menu | Turbo mode | -> on
- [x] "Turbo mode enabled" (toast)
#### 6-1. Home | Menu | Block image | -> on
- [x] "Now showing images" (toast)
#### 6-2. Home | Menu | Block image | -> off
- [x] "Now blocking images" (toast)
#### 7-1. Home | Menu | Settings
- [x] "Language"
- [x] "Default search engine"
- [x] "Clear browsing data"
- [x] "Save downloads to"
- [x] "Make default browser"
- [x] "Send usage data"
- [x] "Mozilla strives to collect only what we need to provide and improve Firefox Rocket for everyone."
- [x] "Learn more"
- [ ] _"Give feedback" (P 1.5)_
- [ ] _"Share with friends" (P 1.5)_
- [x] "About"
#### 7-2. Home | Menu | Settings | Language
- [x] "Language"
- [x] "System default"
- [x] "English"
- [x] "Indonesia" (or "Bahasa Indonesia", use system default)
- [x] "CANCEL"
#### 7-3. Home | Menu | Settings | Default search engine
- [x] "Default search engine"
- [x] "%current_default_search_engine%"
#### 7-4. Home | Menu | Settings | Clear browsing data
- [x] "Browsing history
- [x] "Form history"
- [x] "Cookies"
- [x] "Cache"
- [x] "CANCEL"
- [x] "CLEAR DATA"
#### 7-5. Home | Menu | Settings | Clear browsing data | CLEAR DATA
- [x] "Browsing data cleared" (toast)
#### 7-6. Home | Menu | Settings | Save downloads to
- [x] "Save downloads to"
- [x] "SD card"
- [x] "Internal storage"
- [x] "CANCEL"
#### _7-7. Home | Menu | Settings | Give feedback (P 1.5)_
- [ ] _"Love Firefox Rocket?"_
- [ ] _"Thank you for choosing our product. Your feedback is important to us."_
- [ ] "_Yes, rate 5 star!"_
- [ ] _"No, send feedback"_
#### _7-8. Home | Menu | Settings | Give feedback | No, send feedback (P 1.5)_
- [ ] _"Firefox Rocket"_
- [ ] _"Help us improve the product by giving feedback"_
- [ ] _"say something about performance, easy to use or anything"_
- [ ] _"Submit"_
#### _7-9. Home | Menu | Settings | Share with friends (P 1.5)_
- [ ] _"Share Firefox Rocket with friends!"_
- [ ] _"Fast and lightweight"_
- [ ] _"Helps save data"_
- [ ] _"Powerful screenshots"_
- [ ] _"SHARE"_
#### 7-10. Home | Menu | Settings | About
- [ ] "Firefox Rocket is a fast and lightweight browser produced by Mozilla. Our mission is to foster a healthy, open internet."
- [x] "Learn more"
- [x] "Support"
- [x] "Your Rights"
- [x] "Privacy Notice"
#### 7-11. Home | Menu | Settings | About | Your Rights
- [x] "Firefox Rocket is free and open source software made by Mozilla and other contributors."
- [x] "Firefox Rocket is made available to you under the terms of the Mozilla Public License and other open source licenses."
- [x] "You are not granted any rights or license to the trademarks of the Mozilla Foundation or any party, including the Mozilla, Firefox or Firefox Rocket names or logos. Additional information may be found here."
- [x] "Additional source code for Firefox Rocket is available under various other free and open source licenses."
- [x] "Firefox Rocket also uses blocklists provided by Disconnect, Inc. as separate and independent works under the GNU General Public Licence v3, and available here."
#### 8-1. Home | Menu | Clear cache
- [x] "%file_size% cache cleared" (toast)
#### 8-2. Home | Menu | Capture screenshot | Screenshot saved
- [x] "Screenshot saved" (snack bar - action: SHARE)
#### 8-3. Home | Menu | Capture screenshot | Failed to capture
- [x] "Failed to capture screenshot" (toast)
#### _8-4. Home | System screenshot (P 1.5)_
- [ ] _"Tap the %capture_icon% on the menu to capture the entire page."_
- [ ] _"Use saved screenshots to go back to the page anytime."_
- [ ] _"GOT IT!"_
#### 8-5. Home | Menu | Capture screenshot
- [x] "Capturing screenshot of entire page..."
#### 9-1. Home | Error page
- [x] "Webpage not available"
- [x] "- Make sure you are connected to the internet"
- [x] "- Check the address"
- [x] "TRY AGAIN"
#### 9-2. Home | Error page (app link)
- [x] "The address wasn’t understood"
- [x] "You might need to install other software to open this address."
- [x] "TRY AGAIN"
#### 9-3. Context menu inside Zerda
- [x] "Share link"
- [x] "Copy link address"
- [x] "Share image"
- [x] "Copy image address"
- [x] "Save image"
#### _9-5. Context menu inside Zerda | Download a file | Download using mobile data confirm (P 1.5)_
- [ ] _"file_name*"_
- [ ] _"filesize*"_
- [ ] _"Do you want to download the file over mobile connection?"_
- [ ] _"CANCEL"_
- [ ] _"YES"_
#### 9-6. Context menu inside Zerda | Download a file | Download started
- [x] "Downloading..." (toast)
#### 9-7. Context menu inside Zerda | Download a file | Download finished
- [x] "file_name* downloaded" (toast)
#### _9-8. Context menu inside Zerda | Download a file | Download: No SD card detected_
- [ ] _"No SD card detected. File was saved to internal storage." (toast)_
#### _9-9. Context menu inside Zerda | Download a file | Download: Saved to SD card_
- [ ] _"File saved to SD card" (toast)_
#### _9-10. Context menu inside Zerda | Download a file | Download: SD card is full_
- [ ] _"SD card is almost full. File was saved to internal storage." (toast)_
#### 9-11. Context menu inside Zerda | Download a file | Download: Storage not available
- [x] "Storage inaccessible. Download canceled." (toast)
#### 9-12. Context menu inside Zerda | Download a file | Download: File type not supported
- [x] “File type not supported” (toast)
#### 9-13. Context menu inside Zerda | Download a file | Download: Protocol not supported
- [x] "Download protocol not supported" (toast)
#### 10-1. Context menu from outside app
- [x] "SEARCH IN FIREFOX ROCKET"

**Comment by dakaizou** [comment]
0911
## Not implemented:
#### 2-2. Home | Menu | Downloads with items
- [ ] "failed"
- [ ] "canceled"
- [ ] "paused"
#### 2-4. Home | Menu | Downloads with items | item_menu | Delete file
- [ ] "file_name* was deleted" (snack bar - action: UNDO)
#### 2-5. Home | Menu | Downloads with items | tap on a missing file
- [ ] "Cannot find the file" (toast)
#### 7-1. Home | Menu | Settings
- [ ] "Give feedback"
- [ ] "Share with friends"
#### 7-7. Home | Menu | Settings | Give feedback
- [ ] "Love Firefox Rocket?"
- [ ] "Thank you for choosing our product. Your feedback is important to us."
- [ ] "Yes, rate 5 star!"
- [ ] "No, send feedback"
#### 7-8. Home | Menu | Settings | Give feedback | No, send feedback
- [ ] "Firefox Rocket"
- [ ] "Help us improve the product by giving feedback"
- [ ] "say something about performance, easy to use or anything"
- [ ] "Submit"
#### 7-9. Home | Menu | Settings | Share with friends
- [ ] "Share Firefox Rocket with friends!"
- [ ] "Fast and lightweight"
- [ ] "Helps save data"
- [ ] "Powerful screenshots"
- [ ] "SHARE"
#### 9-3. Context menu inside Zerda | Save image | finished
- [ ] "file_name* finished" (snack bar - action: OPEN)
#### 9-4. Context menu inside Zerda | Download a file | Download using mobile data confirm
- [ ] "file_name*"
- [ ] "filesize*"
- [ ] "Do you want to download the file over mobile connection?"
- [ ] "CANCEL"
- [ ] "YES"
#### 9-6. Context menu inside Zerda | Download a file | Download finished
- [ ] "file_name* downloaded" (snack bar - action: OPEN)
#### 9-7. Context menu inside Zerda | Download a file | Download: No SD card detected
- [ ] "No SD card detected. File was saved to internal storage." (toast)
#### 9-8. Context menu inside Zerda | Download a file | Download: Saved to SD card
- [ ] "File saved to SD card" (toast)
#### 9-9. Context menu inside Zerda | Download a file | Download: SD card is full
- [ ] "SD card is almost full. File was saved to internal storage" (toast)
## Diff:
#### 0-2. Onboarding - second
- [ ] "Our turbo mode blocks ads & trackers for you to enjoy browsing at blazing speed. If a site seems broken, you can turn it off from the menu."
#### 2-2. Home | Menu | Downloads with items
- [ ] "downloading"
#### 3-1. Home | Menu | History empty
- [ ] "No browsing history"
#### 4-1. Home | Menu | My shots | No screenshots
- [ ] "Tap %capture_icon% on the menu to capture an entire web page."
#### 4-3. Home | Menu | My shots | Screenshot item | Delete
- [ ] "Delete this image?"
#### 7-1. Home | Menu | Settings
- [ ] "Mozilla strives to collect only what we need to provide and improve Firefox Rocket for everyone."
#### 7-2. Home | Menu | Settings | Language
- [ ] "English (United States)"
- [ ] "Indonesia"
#### 7-3. Home | Menu | Settings | Default search engine
- [ ] "%current_default_search_engine% (Default)"
#### 7-4. Home | Menu | Settings | Clear browsing data
- [ ] "Cache (file_size*)"
#### 7-6. Home | Menu | Settings | Save downloads to
- [ ] "SD card"
#### 7-10. Home | Menu | Settings | About
- [ ] "Firefox Rocket is a fast and lightweight browser produced by Mozilla. Our missions is to foster a healthy, open internet."
#### 7-11. Home | Menu | Settings | About | Your Rights
- [ ] "Know Your Rights"
- [ ] "Firefox Rocket is free and open source software made by Mozilla and other contributors."
- [ ] "Firefox Rocket is made available to you under the terms of the Mozilla Public License and other open source licenses."
- [ ] "You are not granted any rights or license to the trademarks of the Foundation or any party, including the Mozilla, Firefox or Firefox Rocket names or logos. Additional information may be found here."
- [ ] "Additional source code for Firefox Rocket is available under various other free and open source licenses."
- [ ] "Firefox Rocket also uses blocklists provided by Disconnect, Inc. as separate and independent works under the GNU General Public Licence v3, and available here."
#### 9-1. Home | Error page
- [ ] "Reload"
#### 9-5. Context menu inside Zerda | Download a file | Download started
- [ ] "Downloading..." (toast)

**Comment by Conjuror** [comment]
[dogfooding] The toast "Cannot find the file." -> no need the dot, "Cannot find the file"

**Comment by chianger** [comment]
I think the real blocker will be:

- 2-4, w/o action => Fable team
- 9-4 w/o action => Fable team
- 9-7 w/o action => Fable team
- 9-8, 9-9, 9-10, 9-11, 9-13 @idiotmax @walkingice @mTwTm @WeiWW @Ben-YPLai we need these toast messages

**Comment by Conjuror** [comment]
Let's track 2-4, 9-5, 9-7 with #904

**Comment by chianger** [comment]
#904 covering 2-4, 9-4, and 9-7 are P2, because current build has correct toast messages already.
SD card relevant (9-8, 9-9, 9-10, 9-13) are P2. 9-11 fixed in latest build.

**Comment by dakaizou** [comment]
# 0925
## 1.0 Not ready
#### 2-6. Home | Menu | Downloads with items | downloading_menu | CANCEL
- [ ] "file_name* download canceled" (toast)
#### 7-10. Home | Menu | Settings | About
- [ ] "Firefox Rocket is a fast and lightweight browser produced by Mozilla. Our mission is to foster a healthy, open internet."
#### 9-4. Context menu inside Zerda | Save image | finished
- [ ] "file_name* finished" (toast)
#### 9-8. Context menu inside Zerda | Download a file | Download: No SD card detected
- [ ] "No SD card detected. File was saved to internal storage." (toast)
#### 9-9. Context menu inside Zerda | Download a file | Download: Saved to SD card
- [ ] "File saved to SD card" (toast)
#### 9-10. Context menu inside Zerda | Download a file | Download: SD card is full
- [ ] "SD card is almost full. File was saved to internal storage." (toast)
## Not 1.0
#### 2-2-2. Home | Menu | Downloads with items
- [ ] _"failed"_ (P 1.5)
- [ ] _"canceled"_ (P 1.5)
#### 2-4. _Home | Menu | Downloads with items | item_menu | Delete file (P 1.5)_
- [ ] _"file_name* was deleted" (snack bar - action: UNDO)_
#### 7-1. Home | Menu | Settings
- [ ] _"Give feedback" (P 1.5)_
- [ ] _"Share with friends" (P 1.5)_
#### _7-7. Home | Menu | Settings | Give feedback (P 1.5)_
- [ ] _"Love Firefox Rocket?"_
- [ ] _"Thank you for choosing our product. Your feedback is important to us."_
- [ ] "_Yes, rate 5 star!"_
- [ ] _"No, send feedback"_
#### _7-8. Home | Menu | Settings | Give feedback | No, send feedback (P 1.5)_
- [ ] _"Firefox Rocket"_
- [ ] _"Help us improve the product by giving feedback"_
- [ ] _"say something about performance, easy to use or anything"_
- [ ] _"Submit"_
#### _7-9. Home | Menu | Settings | Share with friends (P 1.5)_
- [ ] _"Share Firefox Rocket with friends!"_
- [ ] _"Fast and lightweight"_
- [ ] _"Helps save data"_
- [ ] _"Powerful screenshots"_
- [ ] _"SHARE"_
#### _8-4. Home | System screenshot (P 1.5)_
- [ ] _"Tap the %capture_icon% on the menu to capture the entire page."_
- [ ] _"Use saved screenshots to go back to the page anytime."_
- [ ] _"GOT IT!"_
#### 9-4. Context menu inside Zerda | Save image | finished
- [ ] "file_name* finished" (snack bar - action: OPEN)
#### _9-5. Context menu inside Zerda | Download a file | Download using mobile data confirm (P 1.5)_
- [ ] _"file_name*"_
- [ ] _"filesize*"_
- [ ] _"Do you want to download the file over mobile connection?"_
- [ ] _"CANCEL"_
- [ ] _"YES"_
#### 9-7. Context menu inside Zerda | Download a file | Download finished
- [ ] "file_name* downloaded" (snack bar - action: OPEN)

**Comment by dakaizou** [comment]
Delete 9-4 since UX spec changed
#### ~~9-4. Context menu inside Zerda | Save image | finished~~ deleted since spec changed
- [ ] ~~"file_name* finished" (toast)~~

**Comment by Conjuror** [comment]
Put 9-8, 9-9, 9-10 to P1.5

**Comment by mTwTm** [comment]
All 1.0 items should be ready now. I'm not sure if we should close this or keep this, though.

**Comment by dakaizou** [comment]
close since P1 finished, track #950 for P1.5 and P2
