### ISSUE TITLE
[Meta] Visual To-Dos

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#628]
*The following to-dos are sorted according to the VD specs.*

#### 1-1. Home UI
- [x] 1-1-1. Gap between search bar and logo is 60dp while gap between search bar and top sites is 36dp. (Big enough devices, height: 600dp+); 43dp/22dp
- [x] 1-1-2. Color of text of top site is #FFFFFF.
- [x] 1-1-3. When the favicon of top sites is smaller than 25×25 px, use the first alphabet of the site name to replace the favicon.
- [x] 1-1-4. Size of favicon of top sites is 25×25 dp.
- [ ] 1-1-5. *Color of favicon color background should be absorted from favicon. Text color is 25% white.*
- [x] 1-1-6. No shadows of top site icons.
#### 1-2. Home Color And Background Color
- [x] 1-2-1. Missing color gradient from top right to bottom left.
- [x] 1-2-2. Missing pattern.svg with transparent effects.
#### 1-3. Main Navigation Bar
- [x] 1-3-1. Home/Menu button should be #272727. They look similar to #0D0D0D now.
- [x] 1-3-2. Should expand the touch area of Menu and Home button to at least 48×48dp if it's feasible. #597 

---

#### 2-1. Search Suggestion
- [x] 2-1-1. Suggestion box should be #E4E4E4. It looks like #CCCCCC now.
- [x] 2-1-2. Text should be #272727. Looks like #000000 now.
- [x] 2-1-3. The gaps between boxes (6dp) should be smaller than the gap between a box and input field (10dp).

---

#### 3-1. Menu Panel UI
- [x] 3-1-1. The gap between icon and text looks slightly larger than it ought to be (13dp, compared to the size of the pressed state box, 74dp)  **[Current version is the one]**
#### 3-2. Action Panel UI
- [x] 3-2-1. Pressed state of background for next, refresh, share and capture buttons.
- [x] 3-2-2. Divider now looks like #DBDBDB instead of #E4E4E4 on VD specs? **[Current version is the one]**

---

#### 4-1. Download Panel UI
- [x] 4-1-1. Main text looks a little bit heavier than Roboto-Light?
- [x] 4-1-2. Text color should be the same as Downloads/History/My shots
- [x] 4-1-3. Divider now looks like #DBDBDB instead of #D7D7DB on VD specs?
- [x] 4-1-4. No "..." for items with long file names in Downloads. #609
#### 4-2. Tab UI
- [x] 4-2-1. Divider now looks like #DBDBDB instead of #E4E4E4 on VD specs?
- [x] 4-2-2. Make _unselected_ tabs be _disabled_ color, #272727 and opacity is 20%.
#### 4-3. Download Empty State
- [x] 4-3-1. There's no gap between icon and text like History's and My Shot's right now. 

---

#### 5-1. History Panel UI
- [x] 5-1-1. Main text looks a little bit heavier than Roboto-Light

---

#### 6-1. Screenshot Viewer
- [x] 6-1-1. Tool Bar should be #41B7E6 and icon is #FFFFFF/#0E86FF/#8DD3F0.  **[Current Version is correct]**
#### 6-2. Screenshot Library Empty State
- [x] 6-2-1. Change icon and texts' color to #737373
- [x] 6-2-2. icon and "no screenshots" is 10 dp
- [x] 6-2-3. "no screenshots" and "Tap ... on the menu to capture an entier web page" is 28 dp

---

### 7. Block Image
- [ ] 7-1-1. _No placeholders for blocked images now.  **[Current Version is limitation]**_

---

### 8. Error Handling
- [x] 8-1-1. Should use a dark (#272727) background, light (#FFFFFF) text, #2AEEC1 title and given SVG/button as VD specs says.

---

### 9. Onboarding **[Current Version is correct]**
- [x] 9-1-1. Text of "NEXT" layer is #0A84FF.
- [x] 9-1-2. The gap between Title and the SVG file (40dp) should be more than as twice as many the gap gap between Title and Body (15dp).
- [x] 9-1-3. The gap between NEXT and card bottom should be slightly bigger than the gap between Title and Body as the former is 20dp and the latter is 15dp.
- [x] 9-1-4. Long button for "NEXT" and "OK, GOT IT!" may not meet Google Material Design standards. I can only find such long buttons for [dropdown buttons](https://material.io/guidelines/components/buttons.html#buttons-persistent-footer-buttons).

---

### 10. General
- [x] 10-1-1. Color theme follow up: system theme color (text selected color/dialogue/Settings/choices). #600 #285

**Comment by Conjuror** [comment]
**[09-06] Backup purpose**

*The following to-dos are sorted according to the VD specs.*

### Home
#### Home UI
- [ ] Gap between search bar and logo is 72dp while gap between search bar and top sites is 36dp. The former should be 2x long then the latter.
- [ ] Color of text of top site is #FFFFFF.
- [ ] When the favicon of top sites is smaller than 25×25 dp, use the first alphabet of the site name to replace the favicon.
- [ ] Size of favicon of top sites is 25×25 dp.
- [ ] Color of favicon color background should be different.
- [ ] The VD spec does not mention about shadows of top site icons.
#### Home Color And Background Color
- [ ] Missing color gradient from top right to bottom left.
- [ ] Missing pattern.svg with transparent effects.
#### Main Navigation Bar
- [ ] Home/Menu button should be #272727. They look similar to #0D0D0D now.
- [ ] Should expand the touch area of Menu and Home button to at least 48×48dp if it's feasible. #597 

---

### Search
#### Search Suggestion
- [ ] Suggestion box should be #E4E4E4. It looks like #CCCCCC now.
- [ ] Text should be #272727. Looks like #000000 now.
- [ ] The gaps between boxes (6dp) should be smaller than the gap between a box and input field (10dp).

---

### Menu
#### Menu Panel UI
- [ ] The gap between icon and text looks slightly larger than it ought to be (13dp, compared to the size of the pressed state box, 74dp).
#### Action Panel UI
- [ ] No pressed state of background for next, refresh, share and capture buttons.
- [ ] Divider now looks like #DBDBDB instead of #E4E4E4 on VD specs?

---

### Download
#### Download Panel UI
- [ ] Main text looks a little bit heavier than Roboto-Light?
- [ ] Divider now looks like #DBDBDB instead of #D7D7DB on VD specs?
- [ ] No "..." for items with long file names in Downloads. #609
#### Tab UI
- [ ] Divider now looks like #DBDBDB instead of #E4E4E4 on VD specs?
#### Download Empty State
- [ ] There's no gap between icon and text like History's and My Shot's right now. 

---

### History
#### History Panel UI
- [ ] Main text looks a little bit heavier than Roboto-Light?

---

### Screenshot Library
#### Screenshot Library Panel
- [ ] Tool Bar should be #41B7E6 and icon is #FFFFFF/#0E86FF/#8DD3F0.
#### Screenshot Library Empty State
- [ ] Icons should be #737373 as they are a part of texts?
- [ ] Action_capture.png looks too high.

---

### Block Image
- [ ] No placeholders for blocked images now. 

---

### Error Handling
- [ ] Should use a dark (#272727) background, light (#737373) text, #2AEEC1 title and given SVG/button as VD specs says.

---

### Onboarding
- [ ] Text of "NEXT" layer is #0A84FF.
- [ ] The gap between Title and the SVG file (40dp) should be more than as twice as many the gap gap between Title and Body (15dp).
- [ ] The gap between NEXT and card bottom should be slightly bigger than the gap between Title and Body as the former is 20dp and the latter is 15dp.
- [ ] Long button for "NEXT" and "OK, GOT IT!" may not meet Google Material Design standards. I can only find such long buttons for [dropdown buttons](https://material.io/guidelines/components/buttons.html#buttons-persistent-footer-buttons).

---

### General
- [ ] Color theme follow up: system theme color (text selected color/dialogue/Settings/choices). #600 #285

**Comment by Conjuror** [comment]
**[09-21] We have a meet up to discuss about the final version**

The final result will be maintained by the top comment of this thread.

**Comment by Conjuror** [comment]
All the highlight color please change to #0a84ff
    Text Highlight fill: #0a84ff ,opacity: 30%
#600

**Comment by cssjh** [comment]
[Screenshots from 1-1-1 to 6-2-3](https://drive.google.com/drive/folders/0B-hmv-8fniTNVmFrS09sV3F6T3c) (only upload unchecked ones, skip 1-1-5)

**Comment by joseph-yar** [comment]
@cssjh Could you grant the access right for me? joseph.yu@yarboroughtech.com

**Comment by cssjh** [comment]
@joseph-yar Anyone who has the link can view now :)

**Comment by cssjh** [comment]
Found some issues on build **1241**:
1. The icons and texts' color of both Downloads & History should be #737373 just like My shots'.
2. Please review the gap problem as the specs [required](https://drive.google.com/file/d/0B-hmv-8fniTNejBZREkxdHlSd00/view?usp=sharing).
3. Text highlight color should be the same when tapping on URL bar when browsing or when a user enter some texts to trigger autocomplete.

Thanks ;)

**Comment by Conjuror** [comment]
According to #729 the selected text should be  #ADE1F5
https://github.com/mozilla-tw/Zerda/issues/729#issuecomment-329738959

> Text selection
> The select box color needs to change to light blue (#ADE1F5) instead of purple. Also for the select handle bar, it should be #0A84FF

**Comment by cssjh** [comment]
**Verified** on 1281.
P1.5+ reference: #956
