### ISSUE TITLE
[Meta] Change toast to snack bar

### ISSUE THREAD

**Issue by dakaizou** [mozilla-tw/Zerda#904]
related: #623 
#### 2-4. Home | Menu | Downloads with items | item_menu | Delete file
- [ ] "file_name* was deleted" (snack bar - action: UNDO)
#### 9-4. Context menu inside Zerda | Save image | finished
- [ ] "file_name* finished" (snack bar - action: OPEN)
#### 9-7. Context menu inside Zerda | Download a file | Download finished
- [ ] "file_name* downloaded" (snack bar - action: OPEN)

**Comment by chianger** [comment]
Currently there are toast with correct messages so let's P2 this.

**Comment by mTwTm** [comment]
Fixed in #910 Note that 9-4 has changed to file_name* downloaded in spec after discussion (see #623 )
