### ISSUE TITLE
[Meta] Visual To-Dos P1.5~

### ISSUE THREAD

**Issue by cssjh** [mozilla-tw/Zerda#956]
*The following to-dos are sorted according to the VD specs.*

#### 1-1. Home UI
- [x] 1-1-1. Gap between search bar and logo is 60dp while gap between search bar and top sites is 36dp. (Big enough devices, height: 600dp+); 43dp/22dp
- [x] 1-1-2. Color of text of top site is #FFFFFF.
- [x] 1-1-3. When the favicon of top sites is smaller than 25×25 px, use the first alphabet of the site name to replace the favicon.
- [x] 1-1-4. Size of favicon of top sites is 25×25 dp.
- [ ] 1-1-5. *Color of favicon color background should be absorted from favicon. Text color is 25% white.*
- [x] 1-1-6. No shadows of top site icons.
#### 1-2. Home Color And Background Color
- [x] 1-2-1. Missing color gradient from top right to bottom left.
- [x] 1-2-2. Missing pattern.svg with transparent effects.
#### 1-3. Main Navigation Bar
- [x] 1-3-1. Home/Menu button should be #272727. They look similar to #0D0D0D now.
- [x] 1-3-2. Should expand the touch area of Menu and Home button to at least 48×48dp if it's feasible. #597 

---

#### 2-1. Search Suggestion
- [x] 2-1-1. Suggestion box should be #E4E4E4. It looks like #CCCCCC now.
- [x] 2-1-2. Text should be #272727. Looks like #000000 now.
- [x] 2-1-3. The gaps between boxes (6dp) should be smaller than the gap between a box and input field (10dp).

---

#### 3-1. Menu Panel UI
- [x] 3-1-1. The gap between icon and text looks slightly larger than it ought to be (13dp, compared to the size of the pressed state box, 74dp)  **[Current version is the one]**
#### 3-2. Action Panel UI
- [x] 3-2-1. Pressed state of background for next, refresh, share and capture buttons.
- [x] 3-2-2. Divider now looks like #DBDBDB instead of #E4E4E4 on VD specs? **[Current version is the one]**

---

#### 4-1. Download Panel UI
- [x] 4-1-1. Main text looks a little bit heavier than Roboto-Light?
- [x] 4-1-2. Text color should be the same as Downloads/History/My shots
- [x] 4-1-3. Divider now looks like #DBDBDB instead of #D7D7DB on VD specs?
- [x] 4-1-4. No "..." for items with long file names in Downloads. #609
#### 4-2. Tab UI
- [x] 4-2-1. Divider now looks like #DBDBDB instead of #E4E4E4 on VD specs?
- [x] 4-2-2. Make _unselected_ tabs be _disabled_ color, #272727 and opacity is 20%.
#### 4-3. Download Empty State
- [x] 4-3-1. There's no gap between icon and text like History's and My Shot's right now. 

---

#### 5-1. History Panel UI
- [x] 5-1-1. Main text looks a little bit heavier than Roboto-Light

---

#### 6-1. Screenshot Viewer
- [x] 6-1-1. Tool Bar should be #41B7E6 and icon is #FFFFFF/#0E86FF/#8DD3F0.  **[Current Version is correct]**
#### 6-2. Screenshot Library Empty State
- [x] 6-2-1. Change icon and texts' color to #737373
- [x] 6-2-2. icon and "no screenshots" is 10 dp
- [x] 6-2-3. "no screenshots" and "Tap ... on the menu to capture an entier web page" is 28 dp

---

### 7. Block Image
- [ ] 7-1-1. _No placeholders for blocked images now.  **[Current Version is limitation]**_

---

### 8. Error Handling
- [x] 8-1-1. Should use a dark (#272727) background, light (#FFFFFF) text, #2AEEC1 title and given SVG/button as VD specs says.
- [ ] 8-1-2. _Please review the gap problem of Error Page as the specs [required](https://drive.google.com/file/d/0B-hmv-8fniTNejBZREkxdHlSd00/view?usp=sharing)._

---

### 9. Onboarding **[Current Version is correct]**
- [x] 9-1-1. Text of "NEXT" layer is #0A84FF.
- [x] 9-1-2. The gap between Title and the SVG file (40dp) should be more than as twice as many the gap gap between Title and Body (15dp).
- [x] 9-1-3. The gap between NEXT and card bottom should be slightly bigger than the gap between Title and Body as the former is 20dp and the latter is 15dp.
- [x] 9-1-4. Long button for "NEXT" and "OK, GOT IT!" may not meet Google Material Design standards. I can only find such long buttons for [dropdown buttons](https://material.io/guidelines/components/buttons.html#buttons-persistent-footer-buttons).

---

### 10. General
- [x] 10-1-1. Color theme follow up: system theme color (text selected color/dialogue/Settings/choices). #600 #285

**Comment by chianger** [comment]
" 1-1-5. Color of favicon color background should be absorted from favicon. Text color is 25% white."
is supposedly done according to @mTwTm .

**Comment by chianger** [comment]
" 7-1-1. No placeholders for blocked images now. [Current Version is limitation]" not to be fixed before Nov.

**Comment by mTwTm** [comment]
"1-1-5" is https://github.com/mozilla-tw/Zerda/issues/958 and is closed already.

**Comment by carol-mozilla** [comment]
8-1-2 it doesn't have serious issue now. we could tweak the layout later.
